DROP DATABASE IF EXISTS actl;
DROP ROLE IF EXISTS actl;

CREATE USER actl PASSWORD 'actl' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE actl
  WITH OWNER = actl
  ENCODING = 'UTF8'
  TABLESPACE = pg_default
  LC_COLLATE = 'en_US.UTF-8'
  LC_CTYPE = 'en_US.UTF-8'
  CONNECTION LIMIT = -1;
